import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import cn from "classnames";
import BottomNavbar from "./components/BottomNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Family Summer Games 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "w-full flex flex-col items-center h-screen")}>
        {children}
        <BottomNavbar />
      </body>
    </html>
  );
}
