import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import cn from "classnames";
import BottomNavbar from "./components/BottomNavbar";
import { SessionProvider } from "next-auth/react";
import { Session, getServerSession } from "next-auth";
import Provider from "../context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Family Summer Games 2024",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={cn(inter.className, "w-full flex flex-col items-center h-screen")}>
        <Provider session={session}>
          {children}
          <BottomNavbar />
        </Provider>
      </body>
    </html>
  );
}
